### ISSUE TITLE
Dart null safety migration

### ISSUE THREAD

**Issue by ElieSol** [jitinder/customtogglebuttons#12]
Hello !
Just wanted to ask if this package will be updated to support null safety ?
Thank you in advance for your response 😊

**Comment by jitinder** [comment]
Hi Ellie, 
The most recent pull request allows Null Safety support. I'll try my best to merge this change ASAP and update documentation accordingly

**Comment by ElieSol** [comment]
Hi @jitinder ,
That's great, thank you ! 😊
